services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html/PHP
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    restart: always
    environment:
      MYSQL_DATABASE: rubis
      MYSQL_USER: rubis
      MYSQL_PASSWORD: rubis
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
